import type { IngestionResult } from "./ingestion";

/**
 * A realistic Agent 1 ingestion payload for an energy conference, used in Demo
 * mode. Intentionally includes a duplicate speaker (different casing + legal
 * suffix) and a non-ICP journalist to exercise dedupe and filtering.
 */
export const demoIngestion: IngestionResult = {
  runId: "demo-gridforward-2026",
  conference: {
    name: "GridForward Summit 2026",
    websiteUrl: "https://example.com/gridforward",
    startDate: "2026-09-03",
    endDate: "2026-09-05",
    location: "Austin, TX, USA",
  },
  sessions: [
    {
      sourceId: "ses-btm",
      title: "Behind-the-meter power for AI data center campuses",
      description: "Onsite generation strategies for high-density compute load.",
      startTime: null,
      endTime: null,
      location: "Main Hall",
      topics: ["power", "data centers", "behind-the-meter", "generation"],
      sourceUrl: "https://example.com/gridforward/agenda",
      sourceUrls: ["https://example.com/gridforward/agenda"],
      speakerSourceIds: ["sp-maya", "sp-maya-dup"],
      extractionConfidence: 0.97,
    },
    {
      sourceId: "ses-grid",
      title: "Grid modernization and interconnection for compute density",
      description: "Transmission and interconnection under rapid load growth.",
      startTime: null,
      endTime: null,
      location: "Room A",
      topics: ["grid", "interconnection", "transmission", "load growth"],
      sourceUrl: "https://example.com/gridforward/agenda",
      sourceUrls: ["https://example.com/gridforward/agenda"],
      speakerSourceIds: ["sp-marcus"],
      extractionConfidence: 0.95,
    },
    {
      sourceId: "ses-procure",
      title: "Owner-led procurement under grid scarcity",
      description: "Procurement models for developers building new capacity.",
      startTime: null,
      endTime: null,
      location: "Room B",
      topics: ["procurement", "capacity", "energy"],
      sourceUrl: "https://example.com/gridforward/agenda",
      sourceUrls: ["https://example.com/gridforward/agenda"],
      speakerSourceIds: ["sp-priya"],
      extractionConfidence: 0.92,
    },
    {
      sourceId: "ses-media",
      title: "Press briefing: the year in energy",
      description: "A journalist's review of the energy news cycle.",
      startTime: null,
      endTime: null,
      location: "Media Room",
      topics: ["energy"],
      sourceUrl: "https://example.com/gridforward/agenda",
      sourceUrls: ["https://example.com/gridforward/agenda"],
      speakerSourceIds: ["sp-jordan"],
      extractionConfidence: 0.8,
    },
  ],
  speakers: [
    {
      sourceId: "sp-maya",
      name: "Maya Chen",
      title: "VP, Infrastructure Development",
      company: "HelioCore Energy",
      bio: "Leads infrastructure development for HelioCore's $1.2B AI campus power program.",
      role: "speaker",
      topics: ["power", "data centers"],
      sourceUrl: "https://example.com/gridforward/speakers/maya-chen",
      sourceUrls: ["https://example.com/gridforward/speakers/maya-chen"],
      sessionSourceIds: ["ses-btm"],
      extractionConfidence: 0.94,
    },
    {
      // Duplicate of Maya from the agenda page: different casing + legal suffix.
      sourceId: "sp-maya-dup",
      name: "MAYA CHEN",
      title: null,
      company: "HelioCore Energy, Inc.",
      bio: null,
      role: "speaker",
      topics: ["generation"],
      sourceUrl: "https://example.com/gridforward/agenda",
      sourceUrls: ["https://example.com/gridforward/agenda"],
      sessionSourceIds: ["ses-btm"],
      extractionConfidence: 0.7,
    },
    {
      sourceId: "sp-marcus",
      name: "Marcus Reed",
      title: "Director, Grid Innovation",
      company: "VoltaXis Utilities",
      bio: "Owns grid modernization initiatives across the VoltaXis service territory.",
      role: "speaker",
      topics: ["grid", "transmission"],
      sourceUrl: "https://example.com/gridforward/speakers/marcus-reed",
      sourceUrls: ["https://example.com/gridforward/speakers/marcus-reed"],
      sessionSourceIds: ["ses-grid"],
      extractionConfidence: 0.91,
    },
    {
      sourceId: "sp-priya",
      name: "Priya Shah",
      title: "Chief Development Officer",
      company: "Mesa Peak Power",
      bio: "C-suite development mandate for new distributed generation capacity.",
      role: "speaker",
      topics: ["procurement", "development"],
      sourceUrl: "https://example.com/gridforward/speakers/priya-shah",
      sourceUrls: ["https://example.com/gridforward/speakers/priya-shah"],
      sessionSourceIds: ["ses-procure"],
      extractionConfidence: 0.9,
    },
    {
      sourceId: "sp-jordan",
      name: "Jordan Blake",
      title: "Staff Writer",
      company: "Energy Daily News",
      bio: "Covers the energy sector for a trade publication.",
      role: "journalist",
      topics: ["energy"],
      sourceUrl: "https://example.com/gridforward/speakers/jordan-blake",
      sourceUrls: ["https://example.com/gridforward/speakers/jordan-blake"],
      sessionSourceIds: ["ses-media"],
      extractionConfidence: 0.85,
    },
  ],
  discoveredEvents: [],
  errors: [],
};
