import type { Conference, SequenceStep, Speaker } from "./contracts";

export const speakers: Speaker[] = [
  {
    id: "maya-chen",
    name: "Maya Chen",
    title: "VP, Infrastructure Development",
    company: "HelioCore Energy",
    conference: "GridForward Summit 2026",
    session: "Behind-the-meter power for AI campuses",
    score: 96,
    tier: "A",
    scoreReason: "Owns a live campus program and is speaking on the exact power constraint Candid can unblock.",
    confidence: 0.94,
    scoreBreakdown: { roleFit: 20, companyFit: 19, topicRelevance: 25, seniority: 14, buyingInfluence: 9, eventProximity: 9 },
    evidence: [
      { label: "Agenda", excerpt: "Behind-the-meter power for AI campuses", sourceUrl: "https://example.com/gridforward/agenda", confidence: 0.98 },
      { label: "Speaker bio", excerpt: "Leads infrastructure development for HelioCore's $1.2B AI campus program.", sourceUrl: "https://example.com/gridforward/speakers/maya-chen", confidence: 0.91 },
    ],
    outreachStage: "T-7",
  },
  {
    id: "marcus-reed",
    name: "Marcus Reed",
    title: "Director, Grid Innovation",
    company: "VoltaXis Utilities",
    conference: "GridForward Summit 2026",
    session: "Grid modernization for compute density",
    score: 91,
    tier: "A",
    scoreReason: "Grid innovation owner with immediate exposure to high-density load growth and interconnection constraints.",
    confidence: 0.91,
    scoreBreakdown: { roleFit: 18, companyFit: 18, topicRelevance: 24, seniority: 13, buyingInfluence: 9, eventProximity: 9 },
    evidence: [{ label: "Agenda", excerpt: "Grid modernization for compute density", sourceUrl: "https://example.com/gridforward/agenda", confidence: 0.96 }],
    outreachStage: "T-2",
  },
  {
    id: "elena-torres",
    name: "Elena Torres",
    title: "Head of Clean Technology",
    company: "Northline Partners",
    conference: "Energy Storage North America",
    session: "Financing storage at scale: LP perspectives",
    score: 88,
    tier: "B",
    scoreReason: "Capital allocation influence and a current storage thesis create a strong project-origination signal.",
    confidence: 0.87,
    scoreBreakdown: { roleFit: 17, companyFit: 18, topicRelevance: 21, seniority: 14, buyingInfluence: 10, eventProximity: 8 },
    evidence: [{ label: "Program", excerpt: "Financing storage at scale", sourceUrl: "https://example.com/esna/program", confidence: 0.93 }],
    outreachStage: "T-14",
  },
  {
    id: "darius-okafor",
    name: "Darius Okafor",
    title: "SVP, Project Delivery",
    company: "ArcSpan Developments",
    conference: "POWERGEN 2026",
    session: "Fast-track delivery for distributed generation",
    score: 86,
    tier: "B",
    scoreReason: "Senior project-delivery leader discussing speed-to-power for distributed assets.",
    confidence: 0.85,
    scoreBreakdown: { roleFit: 19, companyFit: 17, topicRelevance: 20, seniority: 14, buyingInfluence: 9, eventProximity: 7 },
    evidence: [{ label: "Speaker directory", excerpt: "Fast-track delivery for distributed generation", sourceUrl: "https://example.com/powergen/speakers", confidence: 0.9 }],
    outreachStage: "Identified",
  },
  {
    id: "priya-shah",
    name: "Priya Shah",
    title: "Chief Development Officer",
    company: "Mesa Peak Power",
    conference: "Industrial Energy Forum",
    session: "Owner-led procurement under grid scarcity",
    score: 84,
    tier: "B",
    scoreReason: "C-suite development mandate plus a procurement topic tightly aligned to owner's-engineer work.",
    confidence: 0.82,
    scoreBreakdown: { roleFit: 19, companyFit: 16, topicRelevance: 20, seniority: 15, buyingInfluence: 9, eventProximity: 5 },
    evidence: [{ label: "Session page", excerpt: "Owner-led procurement under grid scarcity", sourceUrl: "https://example.com/ief/session/owner-led", confidence: 0.89 }],
    outreachStage: "Identified",
  },
];

export const conferences: Conference[] = [
  { id: "gridforward", name: "GridForward Summit 2026", startDate: "2026-09-03T14:00:00.000Z", endDate: "2026-09-05T22:00:00.000Z", city: "Austin, TX", sourceUrl: "https://example.com/gridforward", speakerCount: 112, qualifiedCount: 36, status: "Analyzed" },
  { id: "esna", name: "Energy Storage North America", startDate: "2026-09-17T15:00:00.000Z", endDate: "2026-09-19T22:00:00.000Z", city: "San Diego, CA", sourceUrl: "https://example.com/esna", speakerCount: 98, qualifiedCount: 28, status: "Analyzed" },
  { id: "powergen", name: "POWERGEN 2026", startDate: "2026-10-08T14:00:00.000Z", endDate: "2026-10-10T22:00:00.000Z", city: "Houston, TX", sourceUrl: "https://example.com/powergen", speakerCount: 156, qualifiedCount: 42, status: "Processing" },
  { id: "industrial", name: "Industrial Energy Forum", startDate: "2026-11-12T15:00:00.000Z", endDate: "2026-11-13T22:00:00.000Z", city: "Denver, CO", sourceUrl: "https://example.com/ief", speakerCount: 74, qualifiedCount: 19, status: "Queued" },
];

export const sequenceSteps: SequenceStep[] = [
  { id: "initial", anchor: "T-14", label: "Context-first introduction", scheduledFor: "2026-08-20T15:00:00.000Z", subject: "Your AI campus power session", status: "Sent" },
  { id: "value", anchor: "T-7", label: "Relevant project insight", scheduledFor: "2026-08-27T15:00:00.000Z", subject: "A delivery pattern worth comparing", status: "Sent" },
  { id: "meet", anchor: "T-2", label: "Meet at the event", scheduledFor: "2026-09-01T15:00:00.000Z", subject: "15 minutes in Austin?", status: "Scheduled" },
  { id: "event", anchor: "Event", label: "In-person opportunity", scheduledFor: "2026-09-03T15:00:00.000Z", subject: null, status: "Opportunity" },
  { id: "followup", anchor: "T+2", label: "Post-event follow-up", scheduledFor: "2026-09-07T15:00:00.000Z", subject: "Picking up our Austin conversation", status: "Planned" },
];

export const funnel = [
  { label: "Identified", value: 617 },
  { label: "Contacted", value: 231 },
  { label: "Replied", value: 69 },
  { label: "Meeting scheduled", value: 18 },
  { label: "Met", value: 11 },
  { label: "Conversation booked", value: 6 },
];
